-- Знайти наймолодшого та найстаршого працівників
SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
FROM worker
ORDER BY BIRTHDAY ASC
LIMIT 1

UNION ALL

SELECT 'ELDEST' AS TYPE, NAME, BIRTHDAY
FROM worker
ORDER BY BIRTHDAY DESC
LIMIT 1;